#!/bin/bash

##########################################
# 
# Find and convert file from folder
# 
#  finding /folder/path *.m4v
# 
# (c) 2018, Edoardo Marchetti <marchetti.edoardo@gmail.com>
# https://github.com/jas31085/Libra_310-Script-Collection
#
##########################################

LogFile="/var/log/FindingConversion"


if [[ ! -z "$(ps -ef | grep $0 | awk '{ print $2 }' )" ]]; then
	echo " Script already running"
	exit 1
fi

if [[ -e "/opt/Convert" ]]; then
	Convert="/opt/Convert"
else
	echo " Script not Found in /opt/"
	exit 1
fi

if [[ -d "$1" ]]; then
	Folder="$1"
else
	echo " Folder not exist"
	exit 1	
fi


TYPE="*.mkv"

if [[ ! "$2" ]]; then
	TYPE="$2"
fi


echo "Start Finding File  " $(date) >> $LogFile
echo ""

find "$Folder" -name "$TYPE" -exec bash -x $Convert {} \; &>> $LogFile

echo "Stop Finding File  " $(date)>> $LogFile
echo "" >> $LogFile
